### ISSUE TITLE
Swapping out pieces

### ISSUE THREAD

**Issue by ArieJones** [gautema/CQRSlite#10]
great project! 
Is there any kind of docs or guidance if we want/need to swap out specific providers? 

So like 
1. What if we would like to use SQL Server as the backend for the event store? 
2. What if we needed to use something like NServiceBus or Azure Service Bus? 

Are these sort of things interchangeable now or would we need to fork and modify the code?  

Cheers!
AJ

**Comment by gautema** [comment]
Hi. And thanks for your interest. Everything should be easy to change out without forking the project. To change out the bus for nservicebus or similar, you would need to make a new interface for the ibus interface and make this into an adapter nservicebus. I don't have an event store other than a very simple one in the sample, so you have to implement this yourself to store to sql server. Use the ieventstore interface. All interfaces are passed in via dependency injection so it should be an easy task.

There aren't much documentation, but there are a few blog posts describing how to use it. https://www.codeproject.com/Articles/991648/CQRS-A-Cross-Examination-Of-How-It-Works
This one explains it good in my opinion. 

Good luck
Gaute

**Comment by ArieJones** [comment]
Sweet! Thanks for the rapid response! ...
