### ISSUE TITLE
Another article about CQRSlite

### ISSUE THREAD

**Issue by bdongus** [gautema/CQRSlite#105]
By accident I found a [new article ](https://www.red-gate.com/simple-talk/dotnet/c-programming/getting-started-with-cqrs-part-3/) about CQRSlite.

It shows a more complex scenario with RabbitMQ. Maybe worth adding it to the already existing links.

**Comment by gautema** [comment]
That looks very thorough. I'll see through it at some point to see if its relevant to add. But looks like it from first glance
