### ISSUE TITLE
Where are the query and event handlers being registered?

### ISSUE THREAD

**Issue by LoyalPotato** [gautema/CQRSlite#106]
I can tell that in this line (39) `registrar.RegisterInAssemblyOf(typeof(InventoryCommandHandlers));` that the command handlers are being registered, but I can't find any reference to an handler like `InventoryListView`.

I'm sorry if this isn't the right place to ask this but I don't know where else to put it.
Thanks

**Comment by gautema** [comment]
Hi. Sorry for the late reply.

The function RegisterInAssemblyOf registers all handlers in the assembly of InventoryCommandHandlers, not just that handler.
