### ISSUE TITLE
How to "rollback" to a specific version?

### ISSUE THREAD

**Issue by bdongus** [gautema/CQRSlite#109]
Hi.
I thought of some kind of undo/restore functionality. Replaying the events to a specific version and using that one as the current one would do the trick.

This could be used to recover from malicious data manipulations/hacking or for a undo functionality in the application.

Example:
Current version is 345. Snapshot was taken at 300. The last 10 changes should be reversed. So version 335 would become Version 346.

But I have no idea how to do that. Any ideas? Thoughts?

**Comment by gautema** [comment]
Hi. Sorry for the late reply.

I haven't done this myself, but I guess the main idea will have to be to create a RollbackEvent, the hard part would be to get the state you want to reset to. Unfortunately there is no built in support for this in CQRSlite, so theres not much help to get there. I guess one solution would be to have the command handler load the aggregate in both states and and pass old version into the current one. It can then get the current state using snapshot functionality or some other trick to get current state in a readable way.

**Comment by bdongus** [comment]
Thanks for the reply and the idea. If I ever implement it I'll let you know. :)
