### ISSUE TITLE
Command execution result

### ISSUE THREAD

**Issue by jk1980** [gautema/CQRSlite#12]
First of all I would like to say that this framework is awesome :-) I used CQRSlite in two projects and I'm very happy. One thing I was missing is information from handler that command was execution properly. I mean some boolean value or structure like CommandExecutionResult { Succeed = true/false, Error = "" } will be helpful. As for now I will throw an exception, but in my opinion it isn't a proper way. So if you have any ideas I can implement them with a pleasure on some fork.

**Comment by caochangjiang** [comment]
I think this could solved by extends a abstract class with delegate method，and actually command handler or event handler 's inner method are just like "Handle(AccountCreatedCommand command)" or "Handle(AccountCreatedEvent event)" ,you could define a abstract class  consist of   insert method and update method and transaction method by delegate,and methods with return type by yourself defined ,like this:

```
public class ExecutionResult {
public bool Succeed{get; }
public string Error{get;}
}


public abstract class AbstractEventHandler {
// T  could be dbconnection 
     public ExecutionResult tryInsert(Func<T,ExecutionResult > action){
            //code like try catch 
           try{
                 //to do some insert 
     
                return new ExecutionResult {Succeed=true,Error=""};
            }
            catch (Exception e)
            {
                 //to do 
                 return  new ExecutionResult {Succeed=false,Error=ex.message};
           }
     }
}
```
and all EventHandlers extends from this class 
```
public AccontEventHandler :AbstractEventHandler,IEventHandler<AccountCreatedEvent> {
       public ExecutionResult  Handler(AccountCreatedEvent message){
            //dbconnection
            return tryInsert(connection=>{
                     //like below
                      return connection.insert(message);
            })
       }
}
```
just like this,you could get the result class ExcutionResult

**Comment by gautema** [comment]
Hi, and thanks for your interest. I do think exceptions is the right way to handle errors, so I will not change the way this is done. An error from the command should not be a common thing, so imho it's the way it should be. If you don't agree, it's great that you have found a way that works for you.
