### ISSUE TITLE
Getting rid of the service locator

### ISSUE THREAD

**Issue by henningst** [gautema/CQRSlite#15]
Hi Gaute!

I'm trying to use [SaasKit.Multitenancy](https://github.com/saaskit/saaskit) together with CQRSlite to add multi tenant support. The goal is to have a separate EventStore for each tenant. 

SaasKit is using DI and a separate `TenantResolver` to resolve the current tenant based on the parameter of your choice. However, when used together with CQRSlite, it looks like the `DependencyResolver` is creating some problems. 

I have added `Tenant` as a constructor param to `InMemoryEventStore`, but since the `InMemoryEventStore` is resolved via the custom CQRSlite `DependencyResolver` it's always null. It seems to me that `DependencyResolver` is only able to resolve stuff that was added to the container when the app starts and that this is a completely separate container than the build-in ASP.NET DI Container.

Would it be possible to get rid of the custom DependencyResolver or handle this in some other way?

I just created a [fork](https://github.com/henningst/CQRSlite/) where the issue can be seen.

Check the following line and see that `tenant` is `null` when `InMemoryEventStore` is created:
https://github.com/henningst/CQRSlite/blob/master/Sample/CQRSCode/WriteModel/InMemoryEventStore.cs#L18

**Comment by gautema** [comment]
Hi.

The current dependency resolver does not auto register any dependencies, so in order for it to give a tenant into the constructor, you have to add `services.AddScoped<Tenant, Tenant>();` into Startup.cs, or with some constructor method. You can of course use another service locator if you want to, or register your commands and events your self. The framework only uses it to get the handlers to the bus.

**Comment by henningst** [comment]
I don't think that's the problem. The `Tenant` is registered and there is a separate resolver that creates a new tenant based on the current HttpContext.

I've done some modifications to try to narrow down the issue (see the latest [commit](https://github.com/henningst/CQRSlite/commit/39a09a9c71ec0409532571a147a6e08bd5670fee)). I've removed the entire SaasKit dependency and just implemented the core parts manually. If you have a look at `Startup.cs`, I have now created a simple factory method for constructing a `Tenant`.

https://github.com/henningst/CQRSlite/blob/master/Sample/CQRSWeb/Startup.cs#L32

The factory method creates a new Tenant and is using IHttpContextAccessor to figure out what tenant to create. I think this is the core of the problem. If I delete the lines 72 and 73 in `Startup.cs` and just return a new `Tenant`, it works just fine and the `Tenant` is properly injected in the `InMemoryEventStore` constructor.

In the controllers, everything works fine also when using `IHttpContextAccessor` in the factory method, but as soon as I send a command and the CQRS framework kicks in, it doesn't work. Do you have any idea why IHttpContextAccessor ends up being null?

**Comment by gautema** [comment]
It looks to me like it isn't the IHttpContextAccessor that is null, but the IHttpContextAccessor.HttpContext in the factory method on some of the requests. It then crashes the factory method and EventStore can't be created. Why the context isn't available in this context, I don't know.

**Comment by henningst** [comment]
Yep, you are right! I added another null check in the for `HttpContext` in the factory method. This prevents it from crashing, but it doesn't solve the real problem. I also have no idea why the httpContext isn't available here. Maybe because the `InProcessBus` is registered as singleton or something. I'll try to dig a bit more to see if I can figure it out.
