### ISSUE TITLE
Incoherency in SpecEventStorage --> Get<T>

### ISSUE THREAD

**Issue by pierrus** [gautema/CQRSlite#16]
```
public IEnumerable<IEvent> Get<T>(Guid aggregateId, int fromVersion)
        {
            return Events.Where(x => x.Version > fromVersion);
        }
```

Is it voluntary that the x.Id == aggregateId is omitted in the event storage test component / Get<T> method ? It causes an **EventsOutOfOrderException** due to the fact that I initialize a test with 2 events in the Given() method, targeting 2 different aggregates.

Updating the method to the following corrected the issue:

```
public IEnumerable<IEvent> Get<T>(Guid aggregateId, int fromVersion)
        {
            return Events.Where(x => x.Version > fromVersion && x.Id == aggregateId);
        }
```

**Comment by gautema** [comment]
You are right. There is a bug here. I submit a fix within a few hours.

**Comment by gautema** [comment]
This is fixed i master now. No reason it was the way it was other than the fact that I have only used it to test one aggregate.
