### ISSUE TITLE
Nice projet, documentation missing

### ISSUE THREAD

**Issue by Bidou44** [gautema/CQRSlite#2]
Your project looks promising.
The main problem is that it's not documented at all...

It would be really good to have a small documentation that explains the core principle, with the event mechanisms for example...  The example you did is really good, but it's not sufficient.

Also, you could explain what is the goal of the Session, how one could interchange Autofact with another DI Framework, how one could bind Entity Framework, if it is possible to use the Window Service Bus instead of the InProcessBus class (or any other similar library), what is the snapshot strategy, and probably a lot more.
And what is the exact difference with Greg Young's project?

Concerning to code, I didn't go into the details, but I saw 2-3 small things:
- Use TimeSpan.FromXXX instead of new TimeSpan(x, x, x....)
- In the LoadAggreate method of the Repository, you could create the Aggregate just before the LoadFromHistory method
- The IEventHandler interface could be contravariant

**Comment by gautema** [comment]
Hi.

I haven't really prioritised creating much documentation, but there is a good resource on how to use the framework here: http://www.codeproject.com/Articles/991648/CQRS-A-Cross-Examination-Of-How-It-Works

This should both explain CQRS and this framework. The differences to Gregs example are quite big. Thats more of a simple example, while this project has made a library out of the example.

As for the code changes you suggested, you are welcome to make a pull request.
