### ISSUE TITLE
Generic Constraints on IEventPublisher/IHandlerRegistrar

### ISSUE THREAD

**Issue by svantreeck** [gautema/CQRSlite#22]
I'm trying to swap out the in-memory event implementations of the InProcessBus with RabbitMQ via the EasyNetQ library, and it's implementation makes sure that functions like Publish<T>/Subscribe<T> take [classes](https://github.com/EasyNetQ/EasyNetQ/blob/master/Source/EasyNetQ/IBus.cs#L136) instead of constraining on an interface.  I have a workaround for Publish/Send that can use a base class; however, I can't seem to get a really non-hackish workaround for RegisterHandler<T>.  The error that I receive is: `The type 'T' must be a reference type in order to use it as parameter 'T' in the generic type or method 'IMessageClient.SubscribeAsync<T>(string, Func<T, Task>)'`

Would it be possible to add the class constraint to the Bus interfaces below?
```
//IHandlerRegistrar:
void RegisterHandler<T>(Func<T, Task> handler) where T : class, IMessage;

//IEventPublisher
Task Publish<T>(T @event) where T : class, IEvent;

//ICommandSender
Task Send<T>(T command) where T : class, ICommand;
```

**Comment by gautema** [comment]
This would probably be OK. I'm not in front of a dev env at the moment, but send a PR, and if everything works out and all tests pass, i can probably merge it in pretty quick.
