### ISSUE TITLE
Is the "Infrastructure" stuff to call "Apply" method by reflection really needed?

### ISSUE THREAD

**Issue by ceferrari** [gautema/CQRSlite#24]
I am taking my first steps into CQRS/ES and I am studying the code of this project.

Looking at the InventoryItem WriteModel supplied in CQRSCode project, we can notice the following methods:
```
        private void Apply(InventoryItemDeactivated e)
        {
            _activated = false;
        }

        public void Deactivate()
        {
            if(!_activated) throw new InvalidOperationException("already deactivated");
            ApplyChange(new InventoryItemDeactivated(Id));
        }
```

When we call the Deactivate method, it calls the ApplyChange method defined in the AggragteRoot base class which will finally call the Apply method at derived class by reflection.

We could merge those methods into:
```
        public void Deactivate()
        {
            if(!_activated) throw new InvalidOperationException("already deactivated");
            _activated = false;
            ApplyChange(new InventoryItemDeactivated(Id));
        }
```

thus eliminating the need of the following line in AggregateRoot's ApplyChange method:
```
this.AsDynamic().Apply(@event);
```

and the Infrastructure folder.

But when I tried applying those changes to the CQRSLite.Tests project, the Domain Test "When_getting_an_aggregate > Should_apply_events()" failed because it uses the TestEventStore which creates a "SavedEvents" list with two TestAggregateDidSomething that were supposed to increment the DidSomethingCount by reflection (using the Apply method).

The only changes I did were removing the Apply method from the TestAggregate and moving the "DidSomethingCount++;" to the DoSomething() method.

As I said, I am new to the CQRS/ES world and I might be wrong, but from my point of view, those events in the TestEventStore list would only be created as a result of the execution of either the DoSomething() or DoSomethingElse() methods, which would validate the test.

Please correct me if I am wrong and sorry for my english.

**Comment by gautema** [comment]
When playing the events back when the aggregate is rehydrated, the Apply method is needed to get into the current state. When you remove the apply-method, there is no way to reach the activated=false state on rehydration. We need to have a known method format, so we can find the correct method on rehydration, and it should not have validation logic in it. That way, the validation can change over time, but the aggregates will still be applied without throwing on rehydration.

**Comment by ceferrari** [comment]
I understand now. Thanks for the clarification @gautema
