### ISSUE TITLE
Async methods should accept a CancellationToken

### ISSUE THREAD

**Issue by DamianReeves** [gautema/CQRSlite#26]
I think it would be useful and make a great deal of sense if the async methods on the various interfaces and their implementations also took in an optional `CancellationToken`. This would include the following interfaces and their implementations:

- `IEventStore`
- `IEventPublisher`
- `ISession`
- `IRepository`
- `ICommandSender`

**Comment by gautema** [comment]
Hi. Sorry for the late reply.

Can you give some info on why you think this would help you? If you want it fast, I would also encourage you to write a pull request as I don't have to much time at the moment.

-gaute

**Comment by DamianReeves** [comment]
I have upstream and downstream implementations which support cancellation, but the interface does not. I'm suggesting just to add it as an optional parameter.

I can work on a PR.

**Comment by gautema** [comment]
Sounds good. A PR would be great

**Comment by gautema** [comment]
Is this what you need?

**Comment by DamianReeves** [comment]
Yeah. Thanks so much.
