### ISSUE TITLE
Why do we need the cache if we don't read from it 

### ISSUE THREAD

**Issue by nourBerro** [gautema/CQRSlite#29]
after i debug the sample project i noticed that the CQRS flow is 
Add Item -> Save to Repository -> Save to the Cache -> Save the event in the Event store

then the read event handler come into play  which save to the read database so 
why do we need to save items in the cache if we will not read from it?

**Comment by gautema** [comment]
The cached aggregate is not used from the read model, but in the write model when the next domain command comes. Then the aggregate needs to be loaded so the domain logic can be executed. The cache may not be needed and may even slow things down if you have few writes on each aggregate, but may come in handy if you have many writes on a few aggregates in a short timeframe. 

Hope this helps your understanding.

**Comment by nourBerro** [comment]
what if an exception accord when the read model save to the read repository because network issue or something else.
how can we undo the save in the write model?

**Comment by gautema** [comment]
If your code is synchronous then you could do the whole thing in one transaction and rollback. If you where to use a asynchronous callback you have to handle errors like that yourself. You probably don't want to undo the write model, but rather retry applying to the read model or do something manually to correct the error.

**Comment by nourBerro** [comment]
Yes you right, if an error accord in read model i should reply the events that we recorded in event store 
but in this case we need an advanced Error Monitring & Notification System
