### ISSUE TITLE
Pull Request for Apply/Emit pattern

### ISSUE THREAD

**Issue by minhhungit** [gautema/CQRSlite#33]
I see that we use dynamic to call Apply method, it loose, we can remove apply method in somewhere without warning from compiler, so I want to implement Apply/Emit pattern into current code:
1. interface IEmit.cs:
```
/// <summary>
/// Marks an aggregate root as an emitter
/// </summary>
public interface IEmit<TEvent> where TEvent : IEvent
{
	/// <summary>
	/// Applies changes to the aggregate root instance
	/// </summary>
	void Apply(TEvent e);
}
```
And use it like this:
```
public partial class TestAggregate : AggregateRoot,
	IEmit<TestAggregateDidSomething>,
        IEmit<AnotherEvent>
{
	...
	
	public void DoSomething()
	{
		Emit(new TestAggregateDidSomething()); // We also change "ApplyChange" => "Emit"
	}
		
	public void Apply(TestAggregateDidSomething e)
	{
		...
	}

        public void Apply(AnotherEvent e)
	{
		...
	}
}
```
Use interface can help us make sure that we implemented event and we can know what event we implemented.

Can I create a pull request for this ?

**Comment by gautema** [comment]
I am a bit uncertain about this change. First, I don't want to change the API, since it would be a change to existing users, so changing ApplyChange to Emit seems unnecessary even if the naming might be better. Second, now it's voluntary to implement apply, and this is a feature, not a bug. If you don't need any data from the event to do validation or perform business logic in the model, there is no need to implement the Apply method.

**Comment by minhhungit** [comment]
> changing ApplyChange to Emit seems unnecessary

agree with you about this, we don't need to change it, we can keep it as "ApplyChange"

yeah, this is just a feature, not bug but it will help us maintain events easier

**Comment by petersondrew** [comment]
The code could be changed to first safely cast to an interface and call apply if it is not null, then attempt the dynamic call if it is null. That may balance the performance with the optional implementation of Apply, without effecting existing code

**Comment by minhhungit** [comment]
If you worry then just add IEmit interface, don't change anything else
