### ISSUE TITLE
Using database

### ISSUE THREAD

**Issue by cmssantos** [gautema/CQRSlite#35]
Hi, please, how can i use a database on sample?

**Comment by gautema** [comment]
I'm a bit uncertain of what you want to know. Are you having trouble with the sample, or do you want to use a real database? In that case, what kind of database?

**Comment by cmssantos** [comment]
Hi, using a real database, in this case SQL Server. 
I do not know how to start a tables creation to write events. I have always worked with the reflection model or database.

**Comment by gautema** [comment]
You can most likely start with storing all events and aggregates in one table. 
https://lostechies.com/gabrielschenker/2015/07/13/event-sourcing-applied-the-repository/ Here is an example that should be easy to make work with the IEventStore api.

**Comment by cmssantos** [comment]
Thank you. I'll work on this article.
