### ISSUE TITLE
Why the command needs to tell the expected version?

### ISSUE THREAD

**Issue by Narvalex** [gautema/CQRSlite#40]

**Comment by gautema** [comment]
This is to support optimistic concurrency

**Comment by Narvalex** [comment]
I understand, but, shouldn't it be optional? Since there are lots of event sourcing implementations that does not wraps the optimistic concurrency check all the way from the read model, but from the aggregate hydration, like the [Microsoft's Patterns a Practice CQRS Journey](https://msdn.microsoft.com/en-us/library/jj554200.aspx)?

**Comment by gautema** [comment]
It is optional. The value is nullable.

**Comment by Narvalex** [comment]
Fair enough. Thanks
