### ISSUE TITLE
Setup Sample without .NET Core DI?

### ISSUE THREAD

**Issue by AlexZeitler** [gautema/CQRSlite#44]
Hi,

how would you set up the sample without .NET Core DI and the DepdencyResolver to simply use it on the console (for demonstration purposes without posting Commands via HTTP)?

**Comment by gautema** [comment]
Hi. 

Without any DI, you would have to register the handlers to the InProcessBus yourself. 
`            var bus = new InProcessBus();
            var handlers = new InventoryCommandHandlers();
            bus.RegisterHandler<CreateInventoryItem>((x, y) => handlers.Handle(x));`
Something like this should work.

**Comment by AlexZeitler** [comment]
Thanks
