### ISSUE TITLE
Issue #50 is not fixed in .Net core 1.0

### ISSUE THREAD

**Issue by jyothi530** [gautema/CQRSlite#54]
Thanks for looking into the issue #50  and fixing it but unfortunately the fix you posted is working only for .Net core 2.0 but it is not working in .Net core 1.0. 
Please find the pull request #53 which contains the sample for .Net core 1.0 and also that shows it is not working. 
To test in .Net core 1.0 I added a 'Name' property to ISession. This property is being set inside the command handler(CreateInventoryItemCommandHandler) when a new inventory is being created I am setting the Name property with the inventory name if it is not empty . When you look at subsequent requests the Name property value is the name of the first inventory item.
Also ServiceProvider class is not available in .Net core 1.0
Can you please look into it.

**Comment by gautema** [comment]
I might get around to look at this, but since it's an issue with an old version of asp.net and not cqrslite, I'm not going to prioritize it very high.

**Comment by gautema** [comment]
Fixed in next release. Is in prerelease now

**Comment by artstalker** [comment]
Hi. Was it released already? I haven't found the commit.

**Comment by gautema** [comment]
It was fixed for the sample in commit 6b469d347254af24b611b96d03e27b5e0dd5fa38
This isn't a change to cqrslite, but in the sample. I don't use .net core 1.1 my self, so haven't done anything to test this.

**Comment by artstalker** [comment]
Thanks for quick response!
 But still I do not get it. This issue #54 was about the fact that #50 has been fix in .Net Core 2.0 only. jyothi530 asked to have a look at it. 5 days later you wrote that is' fixed. But [6b469d3](https://github.com/gautema/CQRSlite/commit/6b469d347254af24b611b96d03e27b5e0dd5fa38) is the original fix for .Net Core 2.0. I don't see any fixes for .Net Core 1.0.

**Comment by gautema** [comment]
I can understand you are confused. I think I must have been myself. I think I meant to comment on another issue when I closed this a few weeks ago, and last night I thought you were talking about 2.0. I have not done anything more with this issue. Sorry about the mix up.

**Comment by artstalker** [comment]
Ok, thanks for the clarification. Actually, we found the way how to fix it in 1.1 .Net Core. At least in the old version of CQRSLite ( we are using 0.12.9). There is DependencyResolver that injected into CQRSLite. We always create a new scope inside this  DependencyResolver when resolving the services and in this way, we avoid singleton behavior for the scoped objects.
![image](https://user-images.githubusercontent.com/2846956/31575057-583b74ea-b0e6-11e7-94d2-7ff202f5beba.png)
