### ISSUE TITLE
Relate to another entity and get it

### ISSUE THREAD

**Issue by miltoncamara** [gautema/CQRSlite#57]
How to relate an entity to another entity? I have to use the AggregationId as Foreign Key or a Id Version data? When I need an specific version  how I do to get it?

**Comment by gautema** [comment]
Hi.

There is no built in way to relate one entity to another. I'm not sure I understand what you want, but you if you want to check if another aggregate exists or has some property, you could load several aggregates in the command handler or query against a read model here.

If you want to get a specific version of an aggregate there is currently no support for it. Again I think I need a bit more context to understand the problem completely.

**Comment by miltoncamara** [comment]
Assuming that I have a product entity and this product is related to an order, at a given time the product value was "100" but today this value is 50. What I would like to know is, what was the value of that order, remembering that it was 50 and today it is 100.

**Comment by gautema** [comment]
I see. I think I would have solved this by saving the value in the order when it was made. It could read of a readmodel. I never do reads from other aggregates directly, but use read models to get their state. Anyway, there is no built in support to this scenario in CQRSlite.
