### ISSUE TITLE
IEventStore - concept of stream

### ISSUE THREAD

**Issue by vaniovanio** [gautema/CQRSlite#59]
Hi,

I am trying to plug Greg Young's EventStore (GES) to the CQRSlite framework with the provided IEventStore interface. Currently I cannot really decide how to proceed with the concept of streams from the GES. In the IEventStore we have: 
`Task Save(IEnumerable<IEvent> events, CancellationToken cancellationToken = default(CancellationToken));`

However, for the GES implementation we also need to provide stream name and expected version, like so:
`Task<WriteResult> AppendToStreamAsync(string stream, long expectedVersion, IEnumerable<EventData> events)`

What course of actions would you recommend in this case?
Thanks in advance!

**Comment by gautema** [comment]
Hi.

Expected version can easily be found by using getting `events.First().Version -1`. Stream name might be a bit trickier depending on how you would name and split your streams, but `Id.ToString()` could be used. If you want something else, you could always create your own custom event type and cast to it in the eventstore and get it from there. 

If none of these works out, you can always fork or copy the needed code from this project and modify it to your need.
