### ISSUE TITLE
Adding new item generates an exception.

### ISSUE THREAD

**Issue by DamenStar** [gautema/CQRSlite#6]
<img width="284" alt="cqrs add" src="https://cloud.githubusercontent.com/assets/367743/19703256/30ca1e4c-9ad1-11e6-85b8-35b4c87359d1.PNG">
![Uploading CQRS Add.PNG…]()
<img width="947" alt="exception" src="https://cloud.githubusercontent.com/assets/367743/19703240/16663efa-9ad1-11e6-82fb-d28f60c03a6b.PNG">
<img width="958" alt="rawexception" src="https://cloud.githubusercontent.com/assets/367743/19703244/1bfdf664-9ad1-11e6-895f-f26cfccc2c0f.PNG">

**Comment by gautema** [comment]
Thanks for the heads up. I just fixed the error.
