### ISSUE TITLE
AggregateFactory is inaccessible due to its protection level

### ISSUE THREAD

**Issue by vaniovanio** [gautema/CQRSlite#60]
Hi,

Working on a repository (IRepository) with eventstore, I am now stuck on the implementation of the LoadAggregate() member, because the AggregateFactory is "internal" in the framework.

What am I missing here?

**Comment by vaniovanio** [comment]
Yes, I am creating a copy of your Repository.cs file and use it for custom repository. Is there a way to use the default implementation instead?

**Comment by gautema** [comment]
The default implementation `Repository` is accessible in the same namespace as IRepository and should be easy to use. No need to copy the code if you are using the nuget package.

**Comment by vaniovanio** [comment]
Thanks! :)
