### ISSUE TITLE
Bug in DynamicInvoker.

### ISSUE THREAD

**Issue by greendimka** [gautema/CQRSlite#62]
IHandler<>.Handle is not called in explicitly implemented ICommandHandler<> classes.

CQRSlite.Infrastructure.DynamicInvoker.GetMember(Type, string, Type[]) incorrectly searches for a method by name.

Dirty fix is coming soon in a pull-request. The issue should not be closed until DynamicInvoker call stack is not fixed/refactored. Currently method name is provided simply as a string. This is bad. For example in VB.NET explicitly implemented interface methods may have names absolutely different from the names declared in interfaces, but they are still valid names, since interface names are used if object is used by an interface-typed variable.
Anyway, I had no time to check all the places where the DynamicInvoker.GetMember is used, but I believe that name as string should be replaced with something more sophisticated OR full name may be used as alternative (i.e. "CQRSlite.Messages.IHandler&lt;SomeCommand&gt;.Handle" instead of "Handle"), but latter approach is a crazy thing.

#63

**Comment by gautema** [comment]
Nice find. I'll look into the issue a bit later. When you continue, I would appreciate a test covering the issue as well.

**Comment by greendimka** [comment]
I just hope I have time to make a full fix and tests, of course. Very busy for the next few weeks.

**Comment by gautema** [comment]
I'm working on a fix my self. Have been able to find a solution for full framework and .net standard 2.0, but still not for lower versions of .net standard since the reflection apis are a bit lacking.

**Comment by greendimka** [comment]
2.0 and full framework can help you with a FindMember method. Standard <2.0 also allows to do the job, but really requires more coding.

**Comment by gautema** [comment]
Since this is fixed on newer platforms with the use of InterfaceMap, I'm closing this. Use full framework or netstandard 2.0 and it works.
