### ISSUE TITLE
Process manager / Sage vs Session

### ISSUE THREAD

**Issue by GuiguiMtl** [gautema/CQRSlite#71]
I am pretty new at CQRS, and I was wondering, as there is no way in CQRS Lite (or at least I don;t see any) to handle long running processes or saga, is this why the Session exists ?
If not, I feel like there is something I don't  understand in CQRSLite. Should we create our process managers/sagas ?

**Comment by gautema** [comment]
Hi.

The session is for short transactions spanning several aggregates. It is not related to a saga in any way. There is no built in way to support sagas in CQRSlite. So you have to do the implementation yourself or use another library to handle the sagas for you.

**Comment by GuiguiMtl** [comment]
Thanks for the fast answer
