### ISSUE TITLE
Support for .Net Standard

### ISSUE THREAD

**Issue by pvredeveld** [gautema/CQRSlite#73]
Hi, can you tell me whether you already adhere to  .Net Standard or is it on the roadmap (By the way, is there a roadmap)?

**Comment by gautema** [comment]
Hi. 

CQRSlite supports .Net Standard. There is compiled versions for 1.3, 1.5 and 2.0. There are a few differences, so use the highest version you can, since there will be some fewer functions in the lower versions.
