### ISSUE TITLE
InProcessBus cannot get the type of sent command if it is generated dynamically

### ISSUE THREAD

**Issue by jonsa** [gautema/CQRSlite#8]
I'm building an API with one endpoint for all commands and use the method [described here](http://stackoverflow.com/a/12641541) to extract which command is being sent.

Here is the code I'm using.

```csharp
[JsonConverter(typeof(JsonCommandConverter))]
public interface IBaseCommand : ICommand
{
    Guid Id { get; set; }
}
```
```csharp
public class FooCommand : BaseCommand
{
}
```
```csharp
class CommandHandler : ICommandHandler<FooCommand>
{
    public void Handle(FooCommand message)
    {
    }
}
```
```csharp
public class CommandsController : ApiController
{
    private InProcessBus _bus;

    public CommandsController()
    {
        var handler = new CommandHandler();

        _bus = new InProcessBus();
        _bus.RegisterHandler<FooCommand>(c =>
        {
            handler.Handle(c);
        });
    }

    public void Post(IBaseCommand command)
    {
        _bus.Send(command);
    }
}
```

Running this will give me a ```FooCommand``` in the Post method but when I send it through the bus I get ```No handler registered```.

This is due to [this line in InProcessBus](https://github.com/gautema/CQRSlite/blob/master/Framework/CQRSlite/Bus/InProcessBus.cs#L27) which uses ```typeof(T)``` which will result in ```IBaseCommand``` in my case. This could be fixed by using ```command.GetType()``` instead.

If this is an acceptable change I can create a pull request.

**Comment by gautema** [comment]
Send a pull request on master with all tests passing, and preferably a new test as well, and I'll merge it in.

**Comment by gautema** [comment]
Thanks for the pull request. Now it's merged and published.
