### ISSUE TITLE
Implement snapshot

### ISSUE THREAD

**Issue by DanBrk** [gautema/CQRSlite#92]
EventStore snapshots is part of CQRSLite and test cases are also included.
I would like know if there is any example of how to add and implement snapshots.

I specially want an example of how to implement **Snapshot** and in **SnapshotAggregateRoot** the abstract methods:
```
protected abstract T CreateSnapshot();
protected abstract void RestoreFromSnapshot(T snapshot);
```

**Comment by managerger** [comment]
It is pretty straightforward. You have to implement `ISnapshotStore` interface, where you have `Get` and `Save` methods which are intended to persist your aggregate snapshot to some storage (use whatever suits your needs the best - db, file etc) and retrieve it later on. Said that, the `CreateSnapshots` should just return a snapshot of your aggregate which will be saved using `ISnapshotStore` 
```
protected override SnapshotMessage CreateSnapshot()
{
     SnapshotMessage snapshot = new SnapshotMessage();
     snapshot.Aggregate = this;
     return snapshot;
}
```

The example of `SnapshotMessage` can be next:
```
public class SnapshotMessage : Snapshot
{
    public YourAggreageteRootType Aggregate { get; set; }
}
```

The next thing that should be done is implementation of `RestoreFromSnapshot` -> this method is invoked right after `Get` method of `ISnapshotStore`. So, its purpose is to restore (read apply) `SnapshotMessage` state to aggregate. Implementation could be the next:
```
protected override void RestoreFromSnapshot(SnapshotMessage snapshot)
{
    this.A = snapshot.Aggregate.A;
    this.B = snapshot.Aggregate.B;
    ............
}
```
That's pretty much it. 

P.S. Keep in mind that you can override default snapshot strategy (how often we should make snapshot and if we should at all). For that purpose implement `ISnapshotStrategy`.

**Comment by gautema** [comment]
As mentioned, it should be pretty straightforward. I usually copy to and
from a memento object with the values you need and save it in a document
store. Remember there is no need to save state you don’t use in your domain
logic.

I don’t have any better examples available than the ones in the test
project, since I’m away traveling for a few days. But I’m available on
mail, so will try my best to help.

**Comment by DanBrk** [comment]
Hi,
Ok, so everything worked as expected.
In addition to the above instruction, I had to fix the IOC to use the SnapshotRepository instead of the regular Repository
Thanks for your help :-)

**Comment by gautema** [comment]
Great to hear it worked out for you.
