### ISSUE TITLE
Service fabric doesn't support GenericHostBuilder

### ISSUE THREAD

**Issue by senthilpalani** [gautema/CQRSlite#95]
I have asp.core 2.2 application Which is hosted in Azure service fabric cluster. I am trying to upgrade to asp.net core 3.1. In 2.2 we register RouteRegistrar in ConfigureServices method. In asp.net core 3.1 sample it is moved to Generic HostBuilder **UseServiceProviderFactory(new RouteRegistrarProviderFactory())**. Currently Service fabric doesn't support Generic HostBuilder. It supports only WebHostBuilder. WebHostBuilder doesn't have **UseServiceProviderFactory** method.

Is there any other way to register with WebHostBuilder?
thanks.

**Comment by gautema** [comment]
Hi.

I don't know much about service fabric, since I've never used it myself. I also had help writing the provider in the sample so my knowledge of this is limited I'm afraid.

**Comment by senthilpalani** [comment]
thanks for speedy response. 
it is working even if i keep the registration old way inside ConfigureService method. But it gives me warning **'Calling 'BuildServiceProvider' from application code results in an additional copy of singleton services being created.**. Will it be problem with additional singleton CQRS services?
if it will not be problem, then i can keep it old way until service fabric support Generic Host.

**Comment by gautema** [comment]
It probably wont matter unless you have a singleton registered where you need to access the same resources from both command and eventhandlers and the web app. There is no problem from CQRSlite's point of view, but it might lead to some hard to find bugs if you write code and forget this gotcha.

**Comment by senthilpalani** [comment]
thanks for suggestion. if i find solution, i will post it here.

**Comment by gautema** [comment]
That would be great. Good luck
