### ISSUE TITLE
Entity Framework Problem

### ISSUE THREAD

**Issue by alansbraga** [gautema/CQRSlite#97]
Hi, I've implemented the IEventStore using Entity Framework and I'm having a problem when I need to access/have two Aggregate accessed when I execute a Command.

The exception is: System.InvalidOperationException: A second operation started on this context before a previous operation completed. This is usually caused by different threads using the same instance of DbContext. For more information on how to avoid threading issues with DbContext, see https://go.microsoft.com/fwlink/?linkid=2097913.

I've created this simple project to show you the problem.
https://github.com/alansbraga/cqrsliteproblem

To avoid this problem I've changed Session.cs line 75 from:
```csharp
tasks[i] = _repository.Save(descriptor.Aggregate, descriptor.Version, cancellationToken);
```
to: 
```csharp
await _repository.Save(descriptor.Aggregate, descriptor.Version, cancellationToken);
```
And, obviously, I removed the:
```csharp
await Task.WhenAll(tasks).ConfigureAwait(false);
```

Do you have any idea what can I do to solve the problem? 
For now, I'm going to copy the Session.cs a change the line the way it works and register my object as ISession on DI.

**Comment by gautema** [comment]
Hi.

I haven't seen this one myself, but I don't use entity framework at the moment. I guess this is something I should fix, since supporting EF is something I want to do. I'll get started on a fix right away. 

Thanks for the bug report.

**Comment by gautema** [comment]
Hi. Have uploaded a patch to nuget. Do you have the possibility to check if it works for you now?

**Comment by gautema** [comment]
Any specific reason for using MediatR and not the Router in CQRSlite by the way?

**Comment by alansbraga** [comment]
Thank you for the quick answer!
I've made the same changes you did, so it'll probably work.
I can test it only on monday.

About MediatR: I'm using its IPipelineBehavior to validate the commands before they get to the Command Handler and send the error back to the API as ModelState errors.

I'll probably use it to verify if the user "can" or "can not" do the Command based on its permissions, but I didn't get there yet.

I'm new to Event Sourcing but this two ideas seems good to me to avoid programmers to forget or to code the same thing every time.

**Comment by alansbraga** [comment]
I've tested now and It worked.
Thank you very much.

If you have any suggestions/questions about the use of MediatR, please, let me know.

**Comment by gautema** [comment]
Great. Glad everything worked out.

I’ll take a look at that feature in mediatr when I have some time. Maybe
there’s something I could draw some inspiration from.

-gaute
