### ISSUE TITLE
Add netstandard2.1 and correct dependencies to match the standards

### ISSUE THREAD

**Issue by mikkelbu** [gautema/CQRSlite#98]
We are using CRQSlite in a .NET Core 2 project. It has been some time since we updated this package, but now we want to use the latest version. However, when we upgraded to 1.31.1 we ran into problems like `Could not load type 'Microsoft.Extensions.Logging.Abstractions.Internal.NullScope' from assembly 'Microsoft.Extensions.Logging.Abstractions, Version=3.1.3.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'.`.

We suspect that the problem is that the `netstandard2.0` target depends on `Microsoft.Extensions.Caching.Memory` version `3.1.3`. Version 3 of Microsoft.Extensions... packages means that this package is for .NET Core 3 as the major version number of the packages should match. We use other packages that depends on other `Microsoft.Extensions....` packages in the latest version 2, and I suspect that this it is this mixup in versions that make our program fail at runtime - e.g. `NullScope` was removed from version 2... to version 3..., so even if we don't use `NullScope` we still fail. We could solve this by taking an explicit dependecy on `Microsoft.Extensions.Logging.Abstractions` version 3.1.3.0 in our project, but as far as I can tell from different sources this is not advisable.

Would you be open for a PR which:
* adds a new netstandard2.1 target which will use `Microsoft.Extensions.Caching.Memory` version `3.1.3` (or 3.1.4 which is now the latest)
* downgrades `Microsoft.Extensions.Caching.Memory` in the netstandard2.0 target, so that it is possible to use in netstandard2.0 projects without running into dependency problems

Some related issues:
* https://stackoverflow.com/questions/56783260/net-standard-2-0-which-microsoft-extensions-dependencyinjection-abstractions
* https://stackoverflow.com/questions/58193023/microsoft-extensions-version-confusion
* https://github.com/serilog/serilog-extensions-logging/issues/158

**Comment by gautema** [comment]
Hi. That sounds good. I’m definitely open to this.

**Comment by mikkelbu** [comment]
Just to be 100% sure :) before the initial cleanup.

It was intended that you deleted the .NET 4.5.2 as a target framework in https://github.com/gautema/CQRSlite/commit/6682c81bb8c1bac16ae90330f59c99210f627a3b. The reason for why I'm asking is that it is still mentioned here
https://github.com/gautema/CQRSlite/blob/5ed5e4f1d824f8d8e9178144ea6f28511a39072c/CQRSlite.nuspec#L34-L35
but the dll and the pdb is no longer build.

**Comment by gautema** [comment]
Hi.

net451 was not supposed to be deleted. That was an error. It's still in the
nuget-file, so I'd like to put it back in the code.

The problem is that I do most of my development on MacOS now, and since the
full framework isn't supported there, I have to remove it to compile. I
create builds on a virtual machine to keep compatibility. Looks like I
slipped up there. I have no idea how many still uses old frameworks, and I
haven't used it myself in years, so I want to remove it eventually, but
maybe not yet.

**Comment by mikkelbu** [comment]
Thanks for the quick release @gautema 👍
